language: node_js
node_js:
  - 12.9.0

cache: yarn

notifications:
  email: false

install:
  - yarn install

jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: test
      script:
        - yarn test

    - stage: build
      script:
        - yarn workspace gatsby-theme-under-construction build
      after_success:
        - yarn workspace gatsby-theme-under-construction audit --perf 90 --pwa 100 --a11y 90 --bp 90 --seo 90 "$(wait-for-netlify-preview)"
