language: node_js
node_js:
  - 10
  - 12

cache: yarn

notifications:
  email: false

install: yarn install

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: test
      script: yarn test

    - stage: build
      script: yarn build

    - stage: publish
      before_deploy:
        - cd theme
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
