language: node_js
node_js:
  - 12.9.0

cache: yarn

notifications:
  email: false

install:
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
        - yarn coverage

    - stage: build
      script:
        - gatsby build
      after_success:
        - yarn run audit --perf 90 --pwa 100 --a11y 90 --bp 90 --seo 90 "$(wait-for-netlify-preview)"
