language: node_js
node_js:
  - 10
  - 12

cache: yarn

notifications:
  email: false

install: yarn install

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: test
      script: yarn test

    - stage: build
      script: yarn build

    - stage: release
      script: skip
      before_deploy:
        - cd theme
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
