# don't build tags, it's redundant
if: tag IS blank

language: node_js
node_js: 12

cache: yarn

notifications:
  email: false

install: yarn install

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: test
      script: yarn test

    - stage: build
      script: yarn build
#    - stage: release
#      # only run on master branch
#      if: NOT type = pull_request AND branch = master
#      script: yarn release
