# don't build tags, it's redundant
if: tag IS blank

language: node_js

node_js:
  - 12
  - 10

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

cache: yarn

notifications:
  email: false

install: yarn install

jobs:
  include:
    - stage: lint
      script: yarn lint

    - stage: test
      script: yarn test

    - stage: build
      script: yarn build

    - stage: release
      script: lerna publish
